services:
  faiss-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server.py:/app/server.py
      - ../../data/faiss_indices:/app/faiss_indices
      - ./PMIDs:/app/PMIDs
    working_dir: /app
    environment:
      - FLASK_APP=server.py
      - FLASK_RUN_HOST=0.0.0.0
    # command: python server.py
